# Generated by Django 5.0.6 on 2025-10-08 22:15

import django_summernote.fields
import django_summernote.utils
import helpers.cloudflare.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_postlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="James Woodhall",
                        help_text="Your full name",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Web Developer & Digital Marketer",
                        help_text="Your professional title",
                        max_length=200,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="woodhalljames@gmail.com",
                        help_text="Contact email",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+1 724-759-4858",
                        help_text="Contact phone number",
                        max_length=50,
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True,
                        default="https://github.com/woodhalljames",
                        help_text="GitHub profile URL",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "professional_image",
                    models.ImageField(
                        blank=True,
                        help_text="Professional headshot photo",
                        upload_to="business/",
                    ),
                ),
                (
                    "resume_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Upload your resume/CV PDF for download",
                        upload_to="business/resumes/",
                    ),
                ),
                (
                    "content",
                    django_summernote.fields.SummernoteTextField(
                        blank=True,
                        help_text="Your professional profile content - add your summary, experience, projects, education, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profile",
            },
        ),
        migrations.CreateModel(
            name="SummernoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Defaults to filename, if left blank",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=helpers.cloudflare.storages.MediaFileStorage(),
                        upload_to=django_summernote.utils.uploaded_filepath,
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Summernote Attachment",
                "verbose_name_plural": "Summernote Attachments",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_summernote.fields.SummernoteTextField(
                help_text="Blog post content with rich text formatting and images"
            ),
        ),
    ]
