# Generated by Django 5.0.6 on 2025-10-08 22:26

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_businessprofile_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="content",
            field=django_summernote.fields.SummernoteTextField(
                blank=True,
                help_text="Your professional profile content - add your summary, experience, projects, education, etc.",
            ),
        ),
    ]
