# Generated by Django 5.0.6 on 2025-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_businessprofile_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Brief professional summary (optional)",
            ),
        ),
    ]
