# Generated by Django 5.0.6 on 2025-10-10 20:31

import helpers.cloudflare.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_businessprofile_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summernoteattachment",
            name="file",
            field=models.FileField(
                storage=helpers.cloudflare.storages.MediaFileStorage(),
                upload_to="summernote/%Y/%m/%d/",
            ),
        ),
    ]
