# Generated by Django 5.0.6 on 2025-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_summernoteattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summernoteattachment',
            name='file',
            field=models.FileField(upload_to='summernote/%Y/%m/%d/'),
        ),
    ]
