# Generated by Django 5.0.6 on 2025-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_summernoteattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='content',
            field=models.TextField(blank=True, help_text='Your professional profile content - add your summary, experience, projects, education, etc.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Blog post content with rich text formatting and images'),
        ),
    ]
